version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  service1:
    build:
      context: ./moviemanagement
    ports:
      - "8081:8080"
    volumes:
      - ./service1:/app
    depends_on:
      - redis

  service2:
    build:
      context: ./recommendation
    ports:
      - "8082:8080"
    volumes:
      - ./service2:/app
    depends_on:
      - redis