version: '3'

services:
  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  # Spring Boot application service
  spring-app:
    build:
      context: ./moviemanagement
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - mynetwork
    volumes:
      - ./moviemanagement/src:/app/src
networks:
  mynetwork:
