version: '3'

services:
  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  # Spring Boot application service
  moviemanagement:
    build:
      context: ./moviemanagement
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - mynetwork
    volumes:
      - ./moviemanagement/src:/app/src
  recc:
    build:
      context: ./recc
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - mynetwork
    volumes:
      - ./recc/src:/app/src
  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - redis
    networks:
      - mynetwork
    volumes:
      - ./apigateway/src:/app/src
  frontend:
    build:
      context: ./frontend
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app

networks:
  mynetwork:
